# Generated by Django 5.0.8 on 2026-05-26 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsession',
            name='description',
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='title',
        ),
    ]
