# Generated by Django 5.0.8 on 2026-06-01 01:11

import apps.StudyMaterial.validator
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batch', '0005_batch_batch_batch_teacher_6c3901_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_material', to='batch.batch')),
                ('upload_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_material', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyMaterialAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='student_material/', validators=[apps.StudyMaterial.validator.validate_file_extension])),
                ('compression_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('original_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('compressed_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('compression_error', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('study_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='StudyMaterial.studymaterial')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_file', models.FileField(blank=True, null=True, upload_to='submitted/', validators=[apps.StudyMaterial.validator.validate_file_extension])),
                ('compression_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('original_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('compressed_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('compression_error', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='StudyMaterial.studymaterial')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='studymaterial',
            index=models.Index(fields=['classroom'], name='StudyMateri_classro_aba142_idx'),
        ),
        migrations.AddIndex(
            model_name='studymaterial',
            index=models.Index(fields=['upload_by'], name='StudyMateri_upload__55af04_idx'),
        ),
        migrations.AddIndex(
            model_name='studymaterial',
            index=models.Index(fields=['upload_at'], name='StudyMateri_upload__dae59f_idx'),
        ),
        migrations.AddIndex(
            model_name='studymaterialattachment',
            index=models.Index(fields=['compression_status'], name='StudyMateri_compres_2fb630_idx'),
        ),
        migrations.AddIndex(
            model_name='studymaterialattachment',
            index=models.Index(fields=['uploaded_at'], name='StudyMateri_uploade_08f24c_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['compression_status'], name='StudyMateri_compres_f1f864_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['submitted_at'], name='StudyMateri_submitt_f34f13_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['assignment', 'student'], name='StudyMateri_assignm_1b1a3c_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='unique_assignment_student'),
        ),
    ]
