# Generated by Django 5.0.8 on 2026-05-25 17:32

import apps.StudyMaterial.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyMaterial', '0002_studymaterialattachment_submission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterialattachment',
            name='file',
            field=models.FileField(upload_to='student_material/', validators=[apps.StudyMaterial.validator.validate_file_extension]),
        ),
    ]
