# Generated by Django 5.0.8 on 2026-05-26 12:24

import apps.StudyMaterial.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyMaterial', '0003_alter_studymaterialattachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_file',
            field=models.FileField(blank=True, null=True, upload_to='submited/', validators=[apps.StudyMaterial.validator.validate_file_extension]),
        ),
    ]
