# Generated by Django 5.0.8 on 2026-05-30 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyMaterial', '0004_submission_submitted_at_submission_submitted_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studymaterial',
            name='description',
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='title',
        ),
    ]
