# Generated by Django 5.0.8 on 2026-05-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyMaterial', '0005_remove_studymaterial_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterialattachment',
            name='compressed_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studymaterialattachment',
            name='compression_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studymaterialattachment',
            name='compression_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='studymaterialattachment',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studymaterialattachment',
            name='original_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='compressed_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='compression_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='submission',
            name='original_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
