# Generated by Django 5.0.8 on 2026-05-30 20:30

import apps.StudyMaterial.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyMaterial', '0006_studymaterialattachment_compressed_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='compression_error',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_file',
            field=models.FileField(blank=True, null=True, upload_to='submitted/', validators=[apps.StudyMaterial.validator.validate_file_extension]),
        ),
    ]
