# Generated by Django 5.0.8 on 2026-05-31 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyMaterial', '0007_submission_compression_error_and_more'),
        ('batch', '0005_batch_batch_batch_teacher_6c3901_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studymaterial',
            index=models.Index(fields=['classroom'], name='StudyMateri_classro_aba142_idx'),
        ),
        migrations.AddIndex(
            model_name='studymaterial',
            index=models.Index(fields=['upload_by'], name='StudyMateri_upload__55af04_idx'),
        ),
        migrations.AddIndex(
            model_name='studymaterial',
            index=models.Index(fields=['upload_at'], name='StudyMateri_upload__dae59f_idx'),
        ),
        migrations.AddIndex(
            model_name='studymaterialattachment',
            index=models.Index(fields=['compression_status'], name='StudyMateri_compres_2fb630_idx'),
        ),
        migrations.AddIndex(
            model_name='studymaterialattachment',
            index=models.Index(fields=['uploaded_at'], name='StudyMateri_uploade_08f24c_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['compression_status'], name='StudyMateri_compres_f1f864_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['submitted_at'], name='StudyMateri_submitt_f34f13_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['assignment', 'student'], name='StudyMateri_assignm_1b1a3c_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='unique_assignment_student'),
        ),
    ]
