services:
  db:
    image: postgres:16-alpine
    container_name: online_class_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: project-backend
    container_name: online_class_backend
    restart: always
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120
      "
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8000"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: "5432"
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: project-nginx
    container_name: online_class_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - static_volume:/staticfiles:ro
      - media_volume:/media:ro
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume: