services:
  db:
    image: postgres:16-alpine
    container_name: online_class_db
    restart: always
    environment:
      POSTGRES_DB: Class
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Kanye@12"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: online_class_backend
    restart: always
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn config.wsgi:application --bind 0.0.0.0:8000 --reload
      "
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8001:8000"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DB_NAME: Class
      DB_USER: postgres
      DB_PASSWORD: "Kanye@12"
      DB_HOST: db
      DB_PORT: "5432"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: online_class_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5170:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 5173

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: online_class_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - static_volume:/staticfiles:ro
      - media_volume:/media:ro
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume: