# Generated by Django 5.0.8 on 2026-05-31 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0004_alter_batch_teacher'),
        ('courses', '0003_course_courses_cou_categor_fec4a4_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['teacher'], name='batch_batch_teacher_6c3901_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['course'], name='batch_batch_course__a65cd4_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['is_active'], name='batch_batch_is_acti_05631c_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['start_date'], name='batch_batch_start_d_0a3dbc_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['teacher', 'is_active'], name='batch_batch_teacher_4114c9_idx'),
        ),
    ]
