# Generated by Django 5.0.8 on 2026-05-22 02:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('PROGRAMMING', 'Programming'), ('DESIGN', 'Design'), ('BUSINESS', 'Business'), ('MARKETING', 'Marketing'), ('DATA_SCIENCE', 'Data Science'), ('LANGUAGE', 'Language'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20)),
                ('duration_weeks', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
