# Generated by Django 5.0.8 on 2026-05-31 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0005_batch_batch_batch_teacher_6c3901_idx_and_more'),
        ('enrollment', '0003_alter_enrollment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['status'], name='enrollment__status_c45c9d_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['batch', 'status'], name='enrollment__batch_i_fd9f6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('batch', 'student'), name='unique_batch_student'),
        ),
    ]
